// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNfgYkEVIDddom5nlAE8Jw-uCNNIMemwo',
    appId: '1:687029654788:web:fcc010b506c95cba90ac51',
    messagingSenderId: '687029654788',
    projectId: 'chatappdemo-62645',
    authDomain: 'chatappdemo-62645.firebaseapp.com',
    storageBucket: 'chatappdemo-62645.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkNIZ534y0uP3pyssT37QduaPoZ56faQA',
    appId: '1:687029654788:android:3406f0630c6deb9390ac51',
    messagingSenderId: '687029654788',
    projectId: 'chatappdemo-62645',
    storageBucket: 'chatappdemo-62645.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNfgYkEVIDddom5nlAE8Jw-uCNNIMemwo',
    appId: '1:687029654788:web:e8cf4bc20396435390ac51',
    messagingSenderId: '687029654788',
    projectId: 'chatappdemo-62645',
    authDomain: 'chatappdemo-62645.firebaseapp.com',
    storageBucket: 'chatappdemo-62645.appspot.com',
  );
}
